name: Deploy to Heroku

on:
  workflow_dispatch:
    inputs:
      HEROKU_APP_NAME:
        description: 'Heroku App name'
        required: true
      BOT_TOKEN:
        description: 'Telegram bot token'
        required: true
      OWNER_ID:
        description: "Owner's telegram ID"
        required: true
      TELEGRAM_API:
        description: 'Telegram API ID from https://my.telegram.org/'
        required: true
      TELEGRAM_HASH:
        description: 'Telegram HASH from https://my.telegram.org/'
        required: true
      SESSION:
      description: ' your pyrogram session'
      required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout deploy branch
        uses: actions/checkout@v2
        with:
          ref: 'refs/heads/deploy'

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{inputs.HEROKU_API_KEY}}
          heroku_app_name: ${{inputs.HEROKU_APP_NAME}}
          heroku_email: ${{inputs.HEROKU_EMAIL}}
          usedocker: true
          docker_heroku_process_type: web
          stack: "container"
          region: "eu"
        env:
          HD_OWNER_ID: ${{inputs.OWNER_ID}}
          HD_TELEGRAM_API: ${{inputs.TELEGRAM_API}}
          HD_TELEGRAM_HASH: ${{inputs.TELEGRAM_HASH}}
          HD_DATABASE_URL: ${{inputs.DATABASE_URL}}
          HD_BOT_TOKEN: ${{inputs.BOT_TOKEN}}
